apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibcapstoneapp-deployment
  labels:
    app: vibcapstoneapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vibcapstoneapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vibcapstoneapp
    spec:
      containers:
        - image: vibhore68/vibcapstoneapp
          imagePullPolicy: Always
          name: vibcapstoneapp
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vibcapstoneapp-lb-service
  labels:
    app: vibcapstoneapp
spec:
  type: LoadBalancer
  selector:
    app: vibcapstoneapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
